name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🚀 Thanks for Contributing!\n\n🎉 Congratulations on raising your first issue for CheakyOS! Your contribution helps us improve.\n\n👀 Keep an eye on your submission. We'll review it soon.\n\n🌟 Happy coding!"
        pr-message: "🚀 Thanks for Contributing!\n\n🎉 Congratulations on raising your first pull request for CheakyOS! Your contribution helps us improve.\n\n👀 Keep an eye on your submission. We'll review it soon.\n\n🌟 Happy coding!"
